# Generated by Django 6.0.3 on 2026-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Guru'), ('student', 'Siswa')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='userimportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
    ]
