# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('retake_available_from', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Belum Mulai'), ('in_progress', 'Sedang Berlangsung'), ('submitted', 'Sudah Submit'), ('auto_submitted', 'Submit Otomatis'), ('grading', 'Sedang Dinilai'), ('completed', 'Selesai')], default='not_started', max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'exam_attempts',
            },
        ),
        migrations.CreateModel(
            name='ExamViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Pindah Tab'), ('fullscreen_exit', 'Keluar Fullscreen'), ('copy_attempt', 'Percobaan Menyalin'), ('paste_attempt', 'Percobaan Menempel'), ('right_click', 'Klik Kanan'), ('suspicious_activity', 'Aktivitas Mencurigakan')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], max_length=20, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_violations',
            },
        ),
        migrations.CreateModel(
            name='ProctoringScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot_url', models.URLField(max_length=500)),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proctoring_screenshots',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_type', models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('matching', 'Matching'), ('fill_in_blank', 'Fill In Blank'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20)),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('answer_order_json', models.JSONField(blank=True, default=list)),
                ('answer_matching_json', models.JSONField(blank=True, default=dict)),
                ('answer_blanks_json', models.JSONField(blank=True, default=dict)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('answer_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.CreateModel(
            name='EssayGrading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='essay_gradings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'essay_gradings',
            },
        ),
    ]
