# Generated by Django 5.2.11 on 2026-02-14 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("submit_time", models.DateTimeField(blank=True, null=True)),
                ("retake_available_from", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("auto_submitted", "Auto Submitted"),
                            ("grading", "Grading"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("passed", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "browser_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_spent_seconds", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_attempts",
            },
        ),
        migrations.CreateModel(
            name="ExamViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab Switch"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("copy_attempt", "Copy Attempt"),
                            ("paste_attempt", "Paste Attempt"),
                            ("right_click", "Right Click"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="attempts.examattempt",
                    ),
                ),
            ],
            options={
                "db_table": "exam_violations",
            },
        ),
        migrations.CreateModel(
            name="ProctoringScreenshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("screenshot_url", models.URLField(max_length=500)),
                ("capture_time", models.DateTimeField(auto_now_add=True)),
                ("file_size_kb", models.IntegerField(blank=True, null=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.TextField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="attempts.examattempt",
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_screenshots",
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("essay", "Essay"),
                            ("short_answer", "Short Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "points_possible",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_marked_for_review", models.BooleanField(default=False)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                ("answer_order", models.IntegerField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="attempts.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="student_answers",
                        to="questions.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_answers",
                        to="questions.questionoption",
                    ),
                ),
            ],
            options={
                "db_table": "student_answers",
            },
        ),
        migrations.CreateModel(
            name="EssayGrading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points_awarded", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="essay_gradings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading",
                        to="attempts.studentanswer",
                    ),
                ),
            ],
            options={
                "db_table": "essay_gradings",
            },
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["exam"], name="idx_exam_attempts_exam_id"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["student"], name="idx_exam_attempts_student_id"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["status"], name="idx_exam_attempts_status"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "student", "attempt_number"],
                name="idx_exam_attempts_retake",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together={("exam", "student", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="examviolation",
            index=models.Index(fields=["attempt"], name="idx_viol_attempt_id"),
        ),
        migrations.AddIndex(
            model_name="examviolation",
            index=models.Index(fields=["detected_at"], name="idx_viol_detected_at"),
        ),
        migrations.AddIndex(
            model_name="examviolation",
            index=models.Index(fields=["violation_type"], name="idx_viol_type"),
        ),
        migrations.AddIndex(
            model_name="proctoringscreenshot",
            index=models.Index(fields=["attempt"], name="idx_ss_attempt_id"),
        ),
        migrations.AddIndex(
            model_name="proctoringscreenshot",
            index=models.Index(fields=["capture_time"], name="idx_ss_capture_time"),
        ),
        migrations.AddIndex(
            model_name="proctoringscreenshot",
            index=models.Index(
                condition=models.Q(("is_flagged", True)),
                fields=["is_flagged"],
                name="idx_ss_flagged",
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(fields=["attempt"], name="idx_stud_ans_attempt_id"),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(fields=["question"], name="idx_stud_ans_question_id"),
        ),
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="essaygrading",
            index=models.Index(fields=["answer"], name="idx_essay_gradings_answer_id"),
        ),
        migrations.AddIndex(
            model_name="essaygrading",
            index=models.Index(
                fields=["graded_by"], name="idx_essay_gradings_graded_by"
            ),
        ),
    ]
