# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examviolation',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='attempts.examattempt'),
        ),
        migrations.AddField(
            model_name='proctoringscreenshot',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='attempts.examattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.examattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='questions.questionoption'),
        ),
        migrations.AddField(
            model_name='essaygrading',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='attempts.studentanswer'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam'], name='idx_exam_attempts_exam_id'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student'], name='idx_exam_attempts_student_id'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='idx_exam_attempts_status'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'student', 'attempt_number'], name='idx_exam_attempts_retake'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='examviolation',
            index=models.Index(fields=['attempt'], name='idx_viol_attempt_id'),
        ),
        migrations.AddIndex(
            model_name='examviolation',
            index=models.Index(fields=['detected_at'], name='idx_viol_detected_at'),
        ),
        migrations.AddIndex(
            model_name='examviolation',
            index=models.Index(fields=['violation_type'], name='idx_viol_type'),
        ),
        migrations.AddIndex(
            model_name='proctoringscreenshot',
            index=models.Index(fields=['attempt'], name='idx_ss_attempt_id'),
        ),
        migrations.AddIndex(
            model_name='proctoringscreenshot',
            index=models.Index(fields=['capture_time'], name='idx_ss_capture_time'),
        ),
        migrations.AddIndex(
            model_name='proctoringscreenshot',
            index=models.Index(condition=models.Q(('is_flagged', True)), fields=['is_flagged'], name='idx_ss_flagged'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt'], name='idx_stud_ans_attempt_id'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question'], name='idx_stud_ans_question_id'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='essaygrading',
            index=models.Index(fields=['answer'], name='idx_essay_gradings_answer_id'),
        ),
        migrations.AddIndex(
            model_name='essaygrading',
            index=models.Index(fields=['graded_by'], name='idx_essay_gradings_graded_by'),
        ),
    ]
