# Generated by Django 5.2.11 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_subject_to_subjects_app"),
        ("exams", "0002_subject_fk_and_question_cascade"),
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="questions.question",
            ),
        ),
    ]

