# Generated by Django 6.0.3 on 2026-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_cascade_exam_and_question_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('not_started', 'Belum Mulai'), ('in_progress', 'Sedang Berlangsung'), ('submitted', 'Sudah Submit'), ('auto_submitted', 'Submit Otomatis'), ('grading', 'Sedang Dinilai'), ('completed', 'Selesai')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='examviolation',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examviolation',
            name='violation_type',
            field=models.CharField(choices=[('tab_switch', 'Pindah Tab'), ('fullscreen_exit', 'Keluar Fullscreen'), ('copy_attempt', 'Percobaan Menyalin'), ('paste_attempt', 'Percobaan Menempel'), ('right_click', 'Klik Kanan'), ('suspicious_activity', 'Aktivitas Mencurigakan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
    ]
