# Generated by Django 6.0.3 on 2026-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_alter_examattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
    ]
