# Generated by Django 6.0.3 on 2026-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_studentanswer_selected_option_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer_order_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
    ]
