# Generated by Django 6.0.3 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_studentanswer_answer_order_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='answer_blanks_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_matching_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('matching', 'Matching'), ('fill_in_blank', 'Fill In Blank'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
    ]
