# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'question_tags',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='questions.questioncategory')),
            ],
            options={
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('matching', 'Matching'), ('fill_in_blank', 'Fill In Blank'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_play_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('video_play_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Mudah'), ('medium', 'Sedang'), ('hard', 'Sulit')], max_length=20, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('checkbox_scoring', models.CharField(choices=[('all_or_nothing', 'Semua atau Nol'), ('partial', 'Parsial dengan Penalti'), ('partial_no_penalty', 'Parsial tanpa Penalti')], default='all_or_nothing', max_length=32)),
                ('allow_previous', models.BooleanField(default=True)),
                ('allow_next', models.BooleanField(default=True)),
                ('force_sequential', models.BooleanField(default=False)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subject')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questioncategory')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_kb', models.IntegerField()),
                ('total_rows', models.IntegerField(default=0)),
                ('total_created', models.IntegerField(default=0)),
                ('total_skipped', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('error_details', models.JSONField(blank=True, default=list, null=True)),
                ('skip_details', models.JSONField(blank=True, default=list, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_import_logs',
            },
        ),
        migrations.CreateModel(
            name='QuestionMatchingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('pair_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='questions.question')),
            ],
            options={
                'db_table': 'question_matching_pairs',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1)),
                ('option_text', models.TextField()),
                ('option_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'db_table': 'question_options',
            },
        ),
        migrations.CreateModel(
            name='QuestionOrderingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_text', models.TextField()),
                ('correct_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='questions.question')),
            ],
            options={
                'db_table': 'question_ordering_items',
            },
        ),
        migrations.CreateModel(
            name='QuestionTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questiontag')),
            ],
            options={
                'db_table': 'question_tag_relations',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords for auto-grading')),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('max_word_count', models.IntegerField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='questions.question')),
            ],
            options={
                'db_table': 'question_answers',
                'indexes': [models.Index(fields=['question'], name='idx_qans_question_id')],
            },
        ),
        migrations.CreateModel(
            name='QuestionBlankAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blank_number', models.PositiveIntegerField()),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('blank_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='questions.question')),
            ],
            options={
                'db_table': 'question_blank_answers',
                'indexes': [models.Index(fields=['question'], name='idx_qblank_question_id'), models.Index(fields=['question', 'blank_number'], name='idx_qblank_number')],
                'unique_together': {('question', 'blank_number')},
            },
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['name'], name='idx_question_categories_name'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['parent'], name='idx_qcat_parent_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by'], name='idx_questions_created_by'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject'], name='idx_questions_subject_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='idx_questions_category_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['question_type'], name='idx_questions_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['difficulty_level'], name='idx_questions_difficulty'),
        ),
        migrations.AddIndex(
            model_name='questionimportlog',
            index=models.Index(fields=['imported_by'], name='idx_qil_imported_by'),
        ),
        migrations.AddIndex(
            model_name='questionimportlog',
            index=models.Index(fields=['status'], name='idx_qil_status'),
        ),
        migrations.AddIndex(
            model_name='questionimportlog',
            index=models.Index(fields=['-created_at'], name='idx_qil_created_at'),
        ),
        migrations.AddIndex(
            model_name='questionmatchingpair',
            index=models.Index(fields=['question'], name='idx_qmatch_question_id'),
        ),
        migrations.AddIndex(
            model_name='questionmatchingpair',
            index=models.Index(fields=['question', 'pair_order'], name='idx_qmatch_order'),
        ),
        migrations.AlterUniqueTogether(
            name='questionmatchingpair',
            unique_together={('question', 'pair_order')},
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='idx_qopt_question_id'),
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('question', 'option_letter')},
        ),
        migrations.AddIndex(
            model_name='questionorderingitem',
            index=models.Index(fields=['question'], name='idx_qord_question_id'),
        ),
        migrations.AddIndex(
            model_name='questionorderingitem',
            index=models.Index(fields=['question', 'correct_order'], name='idx_qord_order'),
        ),
        migrations.AlterUniqueTogether(
            name='questionorderingitem',
            unique_together={('question', 'correct_order')},
        ),
        migrations.AlterUniqueTogether(
            name='questiontagrelation',
            unique_together={('question', 'tag')},
        ),
    ]
