# Generated by Django 5.2.11 on 2026-02-14 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "question_tags",
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="questions.questioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "question_categories",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("essay", "Essay"),
                            ("short_answer", "Short Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                ("allow_previous", models.BooleanField(default=True)),
                ("allow_next", models.BooleanField(default=True)),
                ("force_sequential", models.BooleanField(default=False)),
                ("time_limit_seconds", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="questions.questioncategory",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option_letter",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("option_text", models.TextField()),
                (
                    "option_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("display_order", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
            },
        ),
        migrations.CreateModel(
            name="QuestionTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.questiontag",
                    ),
                ),
            ],
            options={
                "db_table": "question_tag_relations",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subjects",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["name"],
                        name="idx_subjects_name",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions",
                to="questions.subject",
            ),
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_text", models.TextField()),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of keywords for auto-grading",
                    ),
                ),
                ("is_case_sensitive", models.BooleanField(default=False)),
                ("max_word_count", models.IntegerField(blank=True, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correct_answer",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_answers",
                "indexes": [
                    models.Index(fields=["question"], name="idx_qans_question_id")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="questioncategory",
            index=models.Index(fields=["name"], name="idx_question_categories_name"),
        ),
        migrations.AddIndex(
            model_name="questioncategory",
            index=models.Index(fields=["parent"], name="idx_qcat_parent_id"),
        ),
        migrations.AddIndex(
            model_name="questionoption",
            index=models.Index(fields=["question"], name="idx_qopt_question_id"),
        ),
        migrations.AlterUniqueTogether(
            name="questionoption",
            unique_together={("question", "option_letter")},
        ),
        migrations.AlterUniqueTogether(
            name="questiontagrelation",
            unique_together={("question", "tag")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["created_by"], name="idx_questions_created_by"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["subject"], name="idx_questions_subject_id"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["category"], name="idx_questions_category_id"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["question_type"],
                name="idx_questions_type",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["difficulty_level"],
                name="idx_questions_difficulty",
            ),
        ),
    ]
