# Generated by Django 6.0.3 on 2026-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionimportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Mudah'), ('medium', 'Sedang'), ('hard', 'Sulit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionimportlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
    ]
