# Generated by Django 6.0.3 on 2026-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='checkbox_scoring',
            field=models.CharField(choices=[('all_or_nothing', 'Semua atau Nol'), ('partial', 'Parsial dengan Penalti'), ('partial_no_penalty', 'Parsial tanpa Penalti')], default='all_or_nothing', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
    ]
