# Generated by Django 6.0.3 on 2026-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_checkbox_scoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option_letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1),
        ),
    ]
