# Generated by Django 6.0.3 on 2026-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questionoption_option_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_play_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='video_play_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
