# Generated by Django 6.0.3 on 2026-03-10 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_audio_play_limit_question_video_play_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionOrderingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_text', models.TextField()),
                ('correct_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='questions.question')),
            ],
            options={
                'db_table': 'question_ordering_items',
                'indexes': [models.Index(fields=['question'], name='idx_qord_question_id'), models.Index(fields=['question', 'correct_order'], name='idx_qord_order')],
                'unique_together': {('question', 'correct_order')},
            },
        ),
    ]
