# Generated by Django 6.0.3 on 2026-03-10 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_question_type_questionorderingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('checkbox', 'Checkbox'), ('ordering', 'Ordering'), ('matching', 'Matching'), ('fill_in_blank', 'Fill In Blank'), ('essay', 'Esai'), ('short_answer', 'Jawaban Singkat')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionBlankAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blank_number', models.PositiveIntegerField()),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('blank_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='questions.question')),
            ],
            options={
                'db_table': 'question_blank_answers',
                'indexes': [models.Index(fields=['question'], name='idx_qblank_question_id'), models.Index(fields=['question', 'blank_number'], name='idx_qblank_number')],
                'unique_together': {('question', 'blank_number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionMatchingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('pair_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='questions.question')),
            ],
            options={
                'db_table': 'question_matching_pairs',
                'indexes': [models.Index(fields=['question'], name='idx_qmatch_question_id'), models.Index(fields=['question', 'pair_order'], name='idx_qmatch_order')],
                'unique_together': {('question', 'pair_order')},
            },
        ),
    ]
