# Generated by Django 5.2.11 on 2026-02-18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Subject",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("name", models.CharField(max_length=100, unique=True)),
                        ("code", models.CharField(max_length=20, unique=True)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "db_table": "subjects",
                        "ordering": ["name"],
                        "indexes": [
                            models.Index(
                                condition=models.Q(("is_active", True)),
                                fields=["name"],
                                name="idx_subjects_name",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]

