# Generated by Django 6.0.3 on 2026-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='idx_subjects_name',
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='idx_subjects_name'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
    ]
