# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=False)),
                ('allow_review', models.BooleanField(default=True)),
                ('allow_retake', models.BooleanField(default=False)),
                ('max_retake_attempts', models.IntegerField(default=1)),
                ('retake_score_policy', models.CharField(choices=[('highest', 'Nilai Tertinggi'), ('latest', 'Nilai Terakhir'), ('average', 'Rata-rata')], default='highest', max_length=20)),
                ('retake_cooldown_minutes', models.IntegerField(default=0)),
                ('retake_show_review', models.BooleanField(default=False)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('override_question_navigation', models.BooleanField(default=False)),
                ('global_allow_previous', models.BooleanField(default=True)),
                ('global_allow_next', models.BooleanField(default=True)),
                ('global_force_sequential', models.BooleanField(default=False)),
                ('require_fullscreen', models.BooleanField(default=True)),
                ('require_camera', models.BooleanField(default=True)),
                ('require_microphone', models.BooleanField(default=True)),
                ('detect_tab_switch', models.BooleanField(default=True)),
                ('disable_right_click', models.BooleanField(default=True)),
                ('block_copy_paste', models.BooleanField(default=False)),
                ('enable_screenshot_proctoring', models.BooleanField(default=False)),
                ('screenshot_interval_seconds', models.IntegerField(default=300)),
                ('max_violations_allowed', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('published', 'Dipublikasikan'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_type', models.CharField(choices=[('class', 'Kelas'), ('student', 'Siswa')], max_length=20)),
            ],
            options={
                'db_table': 'exam_assignments',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField()),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_navigation', models.BooleanField(default=False)),
                ('allow_previous_override', models.BooleanField(blank=True, null=True)),
                ('allow_next_override', models.BooleanField(blank=True, null=True)),
                ('force_sequential_override', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'db_table': 'classes',
                'indexes': [models.Index(fields=['name'], name='idx_classes_name')],
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_students',
            },
        ),
    ]
