# Generated by Django 5.2.11 on 2026-02-14 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("grade_level", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "classes",
                "db_table": "classes",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["name"],
                        name="idx_classes_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("passing_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("randomize_questions", models.BooleanField(default=False)),
                ("randomize_options", models.BooleanField(default=False)),
                ("show_results_immediately", models.BooleanField(default=False)),
                ("allow_review", models.BooleanField(default=True)),
                ("allow_retake", models.BooleanField(default=False)),
                ("max_retake_attempts", models.IntegerField(default=1)),
                (
                    "retake_score_policy",
                    models.CharField(
                        choices=[
                            ("highest", "Highest"),
                            ("latest", "Latest"),
                            ("average", "Average"),
                        ],
                        default="highest",
                        max_length=20,
                    ),
                ),
                ("retake_cooldown_minutes", models.IntegerField(default=0)),
                ("retake_show_review", models.BooleanField(default=False)),
                ("override_question_navigation", models.BooleanField(default=False)),
                ("global_allow_previous", models.BooleanField(default=True)),
                ("global_allow_next", models.BooleanField(default=True)),
                ("global_force_sequential", models.BooleanField(default=False)),
                ("require_fullscreen", models.BooleanField(default=True)),
                ("detect_tab_switch", models.BooleanField(default=True)),
                ("enable_screenshot_proctoring", models.BooleanField(default=False)),
                ("screenshot_interval_seconds", models.IntegerField(default=300)),
                ("max_violations_allowed", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exams",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to_type",
                    models.CharField(
                        choices=[("class", "Class"), ("student", "Student")],
                        max_length=20,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_assignments",
                        to="exams.class",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_assignments",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_order", models.IntegerField()),
                (
                    "points_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("override_navigation", models.BooleanField(default=False)),
                ("allow_previous_override", models.BooleanField(blank=True, null=True)),
                ("allow_next_override", models.BooleanField(blank=True, null=True)),
                (
                    "force_sequential_override",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="exam_questions",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "exam_questions",
            },
        ),
        migrations.CreateModel(
            name="ClassStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="exams.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_students",
                "indexes": [
                    models.Index(
                        fields=["student"], name="idx_class_students_student_id"
                    )
                ],
                "unique_together": {("class_obj", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["created_by"], name="idx_exams_created_by"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["subject"], name="idx_exams_subject_id"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["status"],
                name="idx_exams_status",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["start_time"], name="idx_exams_start_time"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["end_time"], name="idx_exams_end_time"),
        ),
        migrations.AddIndex(
            model_name="examassignment",
            index=models.Index(fields=["exam"], name="idx_exam_assignments_exam_id"),
        ),
        migrations.AddIndex(
            model_name="examassignment",
            index=models.Index(
                fields=["class_obj"], name="idx_exam_assignments_class_id"
            ),
        ),
        migrations.AddIndex(
            model_name="examassignment",
            index=models.Index(fields=["student"], name="idx_exam_assign_stud_id"),
        ),
        migrations.AddConstraint(
            model_name="examassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assigned_to_type", "class"),
                        ("class_obj__isnull", False),
                        ("student__isnull", True),
                    ),
                    models.Q(
                        ("assigned_to_type", "student"),
                        ("class_obj__isnull", True),
                        ("student__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="valid_assignment_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_retake_attempts__gte", 1), ("max_retake_attempts__lte", 10)),
                name="exam_max_retake_attempts_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("retake_cooldown_minutes__gte", 0)),
                name="exam_retake_cooldown_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(fields=["exam"], name="idx_exam_questions_exam_id"),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["question"], name="idx_exam_questions_question_id"
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["exam", "display_order"], name="idx_exam_questions_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together={("exam", "display_order"), ("exam", "question")},
        ),
    ]
