# Generated by Django 6.0.3 on 2026-03-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        ('results', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_exams', to='results.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='exams.class'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='questions.question'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['student'], name='idx_class_students_student_id'),
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together={('class_obj', 'student')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='idx_exams_created_by'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject'], name='idx_exams_subject_id'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['status'], name='idx_exams_status'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time'], name='idx_exams_start_time'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['end_time'], name='idx_exams_end_time'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_retake_attempts__gte', 1), ('max_retake_attempts__lte', 10)), name='exam_max_retake_attempts_range'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('retake_cooldown_minutes__gte', 0)), name='exam_retake_cooldown_non_negative'),
        ),
        migrations.AddIndex(
            model_name='examassignment',
            index=models.Index(fields=['exam'], name='idx_exam_assignments_exam_id'),
        ),
        migrations.AddIndex(
            model_name='examassignment',
            index=models.Index(fields=['class_obj'], name='idx_exam_assignments_class_id'),
        ),
        migrations.AddIndex(
            model_name='examassignment',
            index=models.Index(fields=['student'], name='idx_exam_assign_stud_id'),
        ),
        migrations.AddConstraint(
            model_name='examassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_type', 'class'), ('class_obj__isnull', False), ('student__isnull', True)), models.Q(('assigned_to_type', 'student'), ('class_obj__isnull', True), ('student__isnull', False)), _connector='OR'), name='valid_assignment_type'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam'], name='idx_exam_questions_exam_id'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['question'], name='idx_exam_questions_question_id'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'display_order'], name='idx_exam_questions_order'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'display_order'), ('exam', 'question')},
        ),
    ]
