# Generated by Django 5.2.11 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_subject_to_subjects_app"),
        ("exams", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_questions",
                to="questions.question",
            ),
        ),
    ]

