# Generated by Django 6.0.3 on 2026-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_subject_fk_and_question_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='retake_score_policy',
            field=models.CharField(choices=[('highest', 'Nilai Tertinggi'), ('latest', 'Nilai Terakhir'), ('average', 'Rata-rata')], default='highest', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draf'), ('published', 'Dipublikasikan'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='assigned_to_type',
            field=models.CharField(choices=[('class', 'Kelas'), ('student', 'Siswa')], max_length=20),
        ),
    ]
