# Generated by Django 6.0.3 on 2026-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_retake_score_policy_alter_exam_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
