# Generated by Django 6.0.3 on 2026-03-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_certificate_enabled'),
        ('results', '0003_certificatetemplate_certificate_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_exams', to='results.certificatetemplate'),
        ),
    ]
