# Generated by Django 6.0.3 on 2026-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='require_camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_microphone',
            field=models.BooleanField(default=True),
        ),
    ]
