# Generated by Django 6.0.3 on 2026-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_exam_disable_right_click"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="block_copy_paste",
            field=models.BooleanField(default=False),
        ),
    ]
