# Generated by Django 6.0.3 on 2026-03-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_block_copy_paste'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='class',
            name='idx_classes_name',
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='idx_classes_name'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='is_active',
        ),
    ]
