# Generated by Django 6.0.3 on 2026-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Sukses'), ('warning', 'Peringatan'), ('error', 'Error'), ('announcement', 'Pengumuman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='log_level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Kritis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('string', 'Teks'), ('number', 'Angka'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=20),
        ),
    ]
